modules/visitor/routes.py
from flask import Flask, render_template, jsonify, request,redirect,url_for, request,flash
import json
from flask import session 
from flask import Blueprint
mod = Blueprint('visitor',__name__,template_folder='templates')
from  modules.visitor import checkword as cw
from modules.visitor.cyberbullying import bullymodel
from modules.database import collection 
from modules.chatbot import chatbot as bot
import modules.news as newsdata
import modules.visitor.checkword as cw
import os


import datetime
from werkzeug.utils import secure_filename
from bson.json_util import dumps


 


ALLOWED_EXTENSIONS = set([ 'jpg', 'jpeg'])


@mod.route('/')
def index():
    if session.get('username') !='':
        return redirect(url_for('visitor.userhome'))
    else:
        return render_template('authentication-signin.html')


@mod.route('/user_auth',methods=['POST'])
def userauth():
    uname = request.form.get('uname')
    password = request.form.get('password')
    status= collection.loginuser(uname,password)
    utype=''
    if status.count() ==1:
        for s in status:
            utype= s['utype']
        if utype =='user':
            session['username'] = uname
            session['logged_in'] = True
            return redirect(url_for('visitor.userhome'))

        elif utype =='admin':
            session['username'] = uname
            session['logged_in'] = True
            return redirect(url_for('admin.home'))
       
    else:
        flash("Invalid username or Password")
        return  redirect(url_for('visitor.index'))
    

@mod.route('/userhome')
def userhome():
    if session['logged_in'] == False:
        return "not logged in"
    online_users = collection.FetchOnlineUsers()
    print(online_users)
    return render_template('userhome.html', online = online_users)




@mod.route('/statusUpdates')
def statusUpdates():
    if session['logged_in'] == False:
        return "not logged in"
    status_updates = collection.fetch_all_status()
    return render_template('statusUpdates.html' ,status = status_updates)
       

@mod.route('/update_settings',methods=['POST'])

def update_settings():
    if session['logged_in'] == False:
        return "not logged in"
    fname = request.form.get('fname')
    lname = request.form.get('lname')
    address = request.form.get('address')
    gender = request.form.get('gender')
    phone = request.form.get('phone')
    email = request.form.get('email')
    job = request.form.get('job')
    place = request.form.get('address')
    rlshp = request.form.get('relationship')
    personal = request.form.get('personal')
    uname= session['username']
    filename =''
    
    try:
        file = request.files['file']
        if file and file.name != '' and allowed_file(file.filename):
            file.filename = file.filename
            filename = file.filename
            file.save(os.path.join(os.getcwd()+'\\modules\\static\\assets\\uploads\\profile\\',file.filename))
    except:
        print("exception in profile upload")
    print(uname)

    status = collection.add_more(uname,fname,lname,email,phone,address,gender,job,rlshp,personal,place,filename,1)
    flash(status)
    return redirect(url_for('visitor.settings'))




@mod.route('/chat')
def chat():
    if session['logged_in'] == False:
        return "not logged in"
    if session['username'] =='':
        return render_template('authentication-signin.html')
    else:
         #chat_history=collection.fetch_chat(session['username'],touser)
         friends = collection.fetch_friends(session['username'])
         return render_template('chatroom.html', frd = friends)

@mod.route('/chat/<touser>',methods=['GET'])
def chatdata(touser):
    if session['logged_in'] == False:
        return "not logged in"
    if session['username'] =='':
        return render_template('authentication-signin.html')
    else:
         chat_history=collection.fetch_chat(session['username'],touser)
         #friends = collection.fetch_friends(session['username'])
         #print(chat_history)
         return dumps(chat_history)
        

@mod.route('/save_chat/<tuser>/<msg>')
def save_chat(tuser,msg):
    id= collection.save_chat(session['username'],tuser,msg)
    collection.update_seen_message(id,session['username'])
    times= datetimes=datetime.datetime.now().strftime("%I:%M%p on %B %d, %Y")
    bully = cw.check_word(msg)
    return jsonify({"msg": msg ,"fuser":session['username'],"times":times,"bully":str(bully)})

@mod.route('/reset')
def reset_password():
    return render_template('authentication-reset-password.html')

@mod.route('/seen/<touser>')
def seen(touser):
    collection.seen(session['username'],touser,session['username'])
    return jsonify({"seen":"yes"})


@mod.route('/recent_chat/<tuser>')
def recent_chat(tuser):
    chat=collection.fetch_chat_recent(session['username'],tuser,session['username'])
    #print(dumps(chat))
    return dumps(chat)

@mod.route('/chatbot')
def chatbot():
    return render_template('chatbot.html')

@mod.route('/messagebot/<msg>')
def messagebot(msg):
    response=bot.response(msg)
    return jsonify({"message":response})

@mod.route('/logout_user',methods=['GET'])
def logout():
    if collection.lougoutUser(session['username']):
        session['logged_in'] = False
        session['username']=''
        
        return render_template('/authentication-signin.html')
    return 'something went wrong during logout........'

        
   

@mod.route('/show_signup')
def signup():
    return render_template('authentication-signup.html')




@mod.route('/myprofile')

def myprofile():
    if session['logged_in'] == False:
        return "not logged in"
     
    status= collection.retrive_status(session['username'])
    settings = collection.fetch_setting(session['username'])
    return render_template('userprofile.html',status_posts = status, setting = settings)



@mod.route('/signup',methods=['POST'])
def add_user():
    uname = request.form.get('uname')
    password = request.form.get('pass')
    email = request.form.get('email')
    phone = request.form.get('phone')
    lname = request.form.get('lname')
    fname = request.form.get('fname')
    status = collection.auth_user(uname,password,email,phone,fname,lname)
    if status == 1 :
        return render_template('authentication-signin.html')
    flash("Username already exists..")
    return render_template('authentication-signup.html')




def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@mod.route('/upload_cover' ,methods=['POST','GET'])

def upload_cover():
     if request.method == 'POST':
        # check if the post request has the file part
        if 'file' not in request.files:
           
            return "someting went wrong 1"
        file = request.files['file']
        # if user does not select file, browser also
        # submit an empty part without filename
        if file.filename == '':
            
            return "something went worng 2" 
        if file and allowed_file(file.filename):
            file.filename = session['username']+".jpg"
            file.save(os.path.join(os.getcwd()+'\\modules\\static\\assets\\uploads\\covers\\',file.filename))
            return redirect(url_for('visitor.myprofile'))


@mod.route('/update_status' , methods=['POST'])
def status():
    uname = request.form.get('uname')
    status = request.form.get('status')
    time= datetime.datetime.now()
    postid = uname+str(time)
    collection.update_status(postid,uname,status,str(time))
    return redirect(url_for('visitor.myprofile'))

@mod.route('/delete_status/<post_id>')
def delete_status(post_id):
    collection.delete_status(post_id)
    return redirect(url_for('visitor.myprofile'))

@mod.route('/searchFriends/<name>')
def searchFriends(name):
    output = dumps(collection.fetchsearch(name))
    return output


@mod.route('/getuserdata')
def getuserdata():
    if session['logged_in']==True:
        data = collection.fetch_setting(session['username'])
        notificationcount = collection.getAllnotificationsCount(session['username'])
        print(session['username'])
    return dumps(data)

@mod.route('/getnoticount')
def getnoticount():
    return jsonify({"count":collection.getAllnotificationsCount(session['username'])})

@mod.route('/sendrequest/<by>/<to>')
def sendrequest(by,to):
    if session['username']=="":
        return url_for('visitor.logout')
    collection.SendFriendRequest(by,to)
    #return jsonify("Friend Request Sent")
    flash("   Freind Request sent ",'info')
    return redirect(url_for('visitor.findf'))

@mod.route('/findf')
def findf():
    if session['logged_in'] == False:
        return "not logged in"
    friendrequestcount = collection.fetch_request_count(session['username'])
    details = collection.fetchDetailsFriendRequests(session['username'])
    return render_template('findf.html',friend = friendrequestcount,detail=details)

@mod.route('/settings')
def settings():
    if session['logged_in'] == False:
        return "not logged in"
    settings = collection.fetch_setting(session['username'])
    return render_template('settings.html' ,setting = settings)

@mod.route('/deletenoti/<id>')
def deletenoti(id):
    collection.deletenotification(id)
    return jsonify({"status":"success"})

@mod.route('/acceptfriend/<frdname>')
def addfriend(frdname):
    collection.AddFriend(session['username'],frdname)
    return redirect(url_for('visitor.findf'))

@mod.route('/rejectfriend/<uname>')
def reject(uname):
    collection.rejectFriend(uname)
    return redirect(url_for('visitor.findf'))

@mod.route('/lost_password',methods=['POST'])
def lost_password():
    if request.method == 'POST':
        mailid = request.json['mailid']
        return collection.lostpassword(mailid)

@mod.route('/notifications/<uname>')
def notifications(uname):
    notifications  = collection.getAllnotifications(uname)

modules/visitor/templates/authentication-signin.html
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from codervent.com/dashtreme/demo/authentication-signin.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 17 Jan 2019 05:45:31 GMT -->
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>
  <title>Dashtreme - Multipurpose Bootstrap4 Admin Template</title>
  <!--favicon-->
  <link rel="icon" href="{{ url_for('static',filename='assets/images/favicon.ico')}}" type="image/x-icon">
  <!-- Bootstrap core CSS-->
  <link href="{{ url_for('static',filename='assets/css/bootstrap.min.css')}}" rel="stylesheet"/>
  <!-- animate CSS-->
  <link href="{{ url_for('static',filename='assets/css/animate.css')}}" rel="stylesheet" type="text/css"/>
  <!-- Icons CSS-->
  <link href="{{ url_for('static',filename='assets/css/icons.css')}}" rel="stylesheet" type="text/css"/>
  <!-- Custom Style-->
  <link href="{{ url_for('static',filename='assets/css/app-style.css')}}" rel="stylesheet"/>
  <script src="{{ url_for('static',filename='assets/js/validations.js')}}"></script>
  <script src="{{ url_for('static',filename='assets/js/sweetalert.min.js')}}"></script>
  
  
  
</head>

<body class="bg-theme bg-theme1">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
       <ul>
          {% for message in messages %}
          <div class="alert" style="padding: 20px;
          background-color: red; /* Red */
          color: white;
          width:300px;
          margin-bottom: 15px;">
           <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
           {{message}}
         </div>
          {% endfor %}
       </ul>
    {% endif %}
   {% endwith %}

<!-- start loader -->
   <div id="pageloader-overlay" class="visible incoming"><div class="loader-wrapper-outer"><div class="loader-wrapper-inner" ><div class="loader"></div></div></div></div>
   <!-- end loader -->

<!-- Start wrapper-->
 <div id="wrapper">

 <div class="loader-wrapper"><div class="lds-ring"><div></div><div></div><div></div><div></div></div></div>
	<div class="card card-authentication1 mx-auto my-5">
		<div class="card-body">
		 <div class="card-content p-2">
		 	<div class="text-center">
		 		<img src="{{ url_for('static',filename='assets/images/logo-icon.png')}}" alt="logo icon">
		 	</div>
		  <div class="card-title text-uppercase text-center py-3">Sign In</div>
		    <form name='signin' action='/user_auth' method="POST">
			  <div class="form-group">
			  <label for="exampleInputUsername" class="sr-only">Username</label>
			   <div class="position-relative has-icon-right">
				  <input type="text" id="uname" name ='uname' class="form-control input-shadow" placeholder="Enter Username">
				  <div class="form-control-position">
					  <i class="icon-user"></i>
				  </div>
			   </div>
			  </div>
			  <div class="form-group">
			  <label for="exampleInputPassword" class="sr-only">Password</label>
			   <div class="position-relative has-icon-right">
				  <input type="password" id="loginPassword" name='password' class="form-control input-shadow" placeholder="Enter Password">
				  <div class="form-control-position">
					  <i class="icon-lock"></i>
				  </div>
			   </div>
			  </div>
			<div class="form-row">
			 <div class="form-group col-6">
			   <div class="icheck-material-white">
                <input type="checkbox" id="user-checkbox" checked="" />
                <label for="user-checkbox">Remember me</label>
			  </div>
			 </div>
			 <div class="form-group col-6 text-right">
			  <a href="{{url_for('visitor.reset_password')}}">Lost Password ?</a>
			 </div>
      </div>

      
      <input type="submit" onclick="return validate_login()" class="btn btn-light btn-block">Sign In</button>
			 
			 
			 </form>
		   </div>
		  </div>
		  <div class="card-footer text-center py-3">
		    <p class="text-warning mb-0">Do not have an account? <a href="{{url_for('visitor.signup')}}"> Sign Up here</a></p>
		  </div>
	     </div>
    


     <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->
	
	<!--start color switcher-->
   <div class="right-sidebar">
    <div class="switcher-icon">
      <i class="zmdi zmdi-settings zmdi-hc-spin"></i>
    </div>
    <div class="right-sidebar-content">

      <p class="mb-0">Gaussion Texture</p>
      <hr>
      
      <ul class="switcher">
        <li id="theme1"></li>
        <li id="theme2"></li>
        <li id="theme3"></li>
        <li id="theme4"></li>
        <li id="theme5"></li>
        <li id="theme6"></li>
      </ul>

      <p class="mb-0">Gradient Background</p>
      <hr>
      
      <ul class="switcher">
        <li id="theme7"></li>
        <li id="theme8"></li>
        <li id="theme9"></li>
        <li id="theme10"></li>
        <li id="theme11"></li>
        <li id="theme12"></li>
      </ul>
      
     </div>
   </div>
  <!--end color cwitcher-->
	
	</div><!--wrapper-->
	
  <!-- Bootstrap core JavaScript-->
  <script src="{{ url_for('static',filename='assets/js/jquery.min.js')}}"></script>
  <script src="{{ url_for('static',filename='assets/js/popper.min.js')}}"></script>
  <script src="{{ url_for('static',filename='assets/js/bootstrap.min.js')}}"></script>
	
  <!-- sidebar-menu js -->
  <script src="{{ url_for('static',filename='assets/js/sidebar-menu.js')}}"></script>
  
  <!-- Custom scripts -->
  <script src="{{ url_for('static',filename='assets/js/app-script.js')}}"></script>
  
</body>

<!-- Mirrored from codervent.com/dashtreme/demo/authentication-signin.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 17 Jan 2019 05:45:31 GMT -->
</html>

modules/visitor/templates/index1.html
<!doctype html>
<html lang="en">
	
<!-- Mirrored from bootstrap.gallery/unify-admin/design-13/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 24 Jan 2019 06:02:52 GMT -->
<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="Unify Admin Panel" />
		<meta name="keywords" content="Analytics, CRM, Admin, Dashboard, Bootstrap4, Sass, CSS3, HTML5, Responsive Dashboard, Responsive Admin Template, Admin Template, Best Admin Template, Bootstrap Template, Themeforest" />
		<meta name="author" content="Bootstrap Gallery" />
		<link rel="shortcut icon" href="{{ url_for('static',filename='assets/admin/img/favicon.ico')}}"/>
		<title>Unify Admin Dashboard - Analytics</title>

		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
		
		<!-- Common CSS -->
		<!-- Common CSS -->
		<link rel="stylesheet" href="{{ url_for('static',filename='assets/admin/fonts/icomoon/icomoon.css')}}" />
		<link rel="stylesheet" href="{{ url_for('static',filename='assets/admin/css/bootstrap.min.css')}}" />
		<link rel="stylesheet" href="{{ url_for('static',filename='assets/admin/css/fonts/icomoon/icomoon.css')}}" />
		<link rel="stylesheet" href="{{ url_for('static',filename='assets/admin/css/main.css')}}" />

		<!-- Other CSS includes plugins - Cleanedup unnecessary CSS -->
		<!-- Chartist CSS -->
		<link href="{{ url_for('static',filename='assets/admin/vendor/chartist/css/chartist.min.css')}}" rel="stylesheet" />
		<link href="{{ url_for('static',filename='assets/admin/vendor/chartist/css/chartist-custom.css')}}" rel="stylesheet" />		
		<script src="{{ url_for('static',filename='assets/js/load.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/js/sendmessage.js')}}"></script> 
		<script src="{{ url_for('static',filename='assets/js/notificationsUser.js')}}"></script> 
		<script src="{{ url_for('static',filename='assets/js/sendmessageChatbot.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/css/usercard.css')}}"></script>
	</head>
	<body onload="fetchsearch()">

		<!-- Loading starts -->
		
		<!-- Loading ends -->
		
		<!-- BEGIN .app-wrap -->
		<div class="app-wrap">
			<!-- BEGIN .app-heading -->
			<header class="app-header">
				<div class="container-fluid">
					<div class="row ">
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-8 col-8">
							<a href="{{url_for('visitor.userhome')}}" class="logo" style="color:white"><strong>SOCIAL HUB</strong>
						
							</a><a class="mini-nav-btn" href="#" id="app-side-mini-toggler">
								<i class="icon-sort"></i>
							</a>
							<a href="#app-side" data-toggle="onoffcanvas" class="onoffcanvas-toggler" aria-expanded="true">
								<i class="icon-chevron-thin-left"></i>
							</a>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-4 col-4">
							<ul class="header-actions">
								<li class="dropdown">
									<a href="http://localhost:5000/notifications/{{session['username']}}" id="notifications" data-toggle="dropdown" aria-haspopup="true">
										<i class="icon-notifications_none" id="noticount" style="font-size:18px"> Notifications</i>
										</span>
									</a>
									<div class="dropdown-menu dropdown-menu-right lg" aria-labelledby="notifications">
										<ul class="imp-notify">
											
												<div class="details">
													<p><span>Wilson</span> The best Dashboard design I have seen ever.</p>
												</div>
											</li>
											<li>
												<div class="icon">J</div>
												<div class="details">
													<p><span>John Smith</span> Jhonny sent you a message. Read now!</p>
												</div>
											</li>
											<li>
												<div class="icon secondary">R</div>
												<div class="details">
													<p><span>Justin Mezzell</span> Stella, Added you as a Friend. Accept it!</p>
												</div>
											</li>
										</ul>
									</div>
								</li>
								<li>
									<a href="{{url_for('visitor.chatbot')}}" id="todos" data-toggle="dropdown" aria-haspopup="true">
										<i class="icon-person_outline" style="font-size:18px"> ChatBot</i>
									</span>
									</a>
									<div class="dropdown-menu dropdown-menu-right lg" aria-labelledby="todos">
										<ul class="stats-widget">
				              <li>
				                <h4>$37895</h4>
				                <p>Revenue <span>+2%</span></p>
				                <div class="progress">
													<div class="progress-bar" role="progressbar" aria-valuenow="87" aria-valuemin="0" aria-valuemax="100" style="width: 87%">
														<span class="sr-only">87% Complete (success)</span>
													</div>
												</div>
				              </li>
				              <li>
				                <h4>4,897</h4>
				                <p>Downloads <span>+39%</span></p>
				                <div class="progress">
													<div class="progress-bar" role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100" style="width: 65%">
														<span class="sr-only">65% Complete (success)</span>
													</div>
												</div>
				              </li>
				              <li>
				                <h4>2,219</h4>
				                <p>Uploads <span class="text-secondary">-7%</span></p>
				                <div class="progress">
													<div class="progress-bar bg-danger" role="progressbar" aria-valuenow="42" aria-valuemin="0" aria-valuemax="100" style="width: 42%">
														<span class="sr-only">42% Complete (success)</span>
													</div>
												</div>
				              </li>
				            </ul>
				          </div>
								</li>
								<li class="dropdown">
									<a href="{{url_for('visitor.settings')}}" id="userSettings" class="user-settings" data-toggle="dropdown" aria-haspopup="true">
									
										<i class="icon-chevron-small-down" style="font-size:18px"> Update Your Bio</i>
									</a>
									<div class="dropdown-menu lg dropdown-menu-right" aria-labelledby="userSettings">
										<ul class="user-settings-list">
											<li>
												<a href="profile.html">
													<div class="icon">
														<i class="icon-account_circle"></i>
													</div>
													<p>Profile</p>
												</a>
											</li>
											<li>
												<a href="profile.html">
													<div class="icon red">
														<i class="icon-cog3"></i>
													</div>
													<p>Settings</p>
												</a>
											</li>
											<li>
												<a href="filters.html">
													<div class="icon yellow">
														<i class="icon-schedule"></i>
													</div>
													<p>Activity</p>
												</a>
											</li>
										</ul>
										<div class="logout-btn">
											<a href="login.html" class="btn btn-primary">Logout</a>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</header>
			<!-- END: .app-heading -->
			<!-- BEGIN .app-container -->
			<div class="app-container">
				<!-- BEGIN .app-side -->
				<aside class="app-side" id="app-side">
					<!-- BEGIN .side-content -->
					<div class="side-content ">
						<!-- BEGIN .user-profile -->
						<div class="user-profile">
							<img src="{{ url_for('static',filename='assets/admin/img/user.png')}}" id="propic_master" class="profile-thumb" alt="User Thumb">
							<br>
							<br>
							<br>
							
							<h5 class="profile-name" id="username_master">-----</h5>
							<h6 class="profile-name"  id="ph_master">-----</h6>
							<h6 class="profile-name" id="email_master">-----</h6>
							<br>
							<br>
							<br>
							
							

							
							<ul class="profile-actions">
								<li>
									<a>
										<i></i>
										<span></span>
									</a>
								</li>
								<li>
									<a>
										<ir"></i>
									</a>
								</li>
								<li>
									<a>
										<i></i>
									</a>
								</li>
							</ul>
							<br>
							<br>
							<br>
							<br>
							<br>
						</div>
						<!-- END .user-profile -->
						<!-- BEGIN .side-nav -->
						<nav class="side-nav">
							<!-- BEGIN: side-nav-content -->
							<ul class="unifyMenu" id="unifyMenu">
								<li class="active selected">
									<a href="#" class="has-arrow" aria-expanded="false">
										<span class="has-icon">
											<i class="icon-laptop_windows"></i>
										</span>
										<span >Menu</span>
									</a>
									<ul aria-expanded="false" class="collapse in">
										
										<li>
											<a href="{{url_for('visitor.userhome')}}"> <br>Friends <br>
												</a>
											
										</li>
										<li>
											<a href="{{url_for('visitor.findf')}}"> <br>Find Friends <br></a>
										</li>
										<li>
											<a href="{{url_for('visitor.chat')}}"><br>Chat<br></a>
										</li>
										<li>
											<a href="{{url_for('visitor.statusUpdates')}}"><br>Status Updates<br></a>
										</li>

										<li>
												<a href="{{url_for('visitor.myprofile')}}" ><br>My profile<br></a>
											</li>

										
											<li>
												<a href="{{url_for('visitor.news')}}"><br>News<br></a>
											</li>

											<li>
												<a href="{{url_for('visitor.logout')}}"><br>Logout<br> <br> <br></a>
											</li>
          
											<li>
													
											</li>
									  
									  
									</ul>
								</li>
							
									</ul>
								</li>
							</ul>
							<!-- END: side-nav-content -->
						</nav>
						<!-- END: .side-nav -->
					</div>
					<!-- END: .side-content -->
				</aside>
				<!-- END: .app-side -->

				<!-- BEGIN .app-main -->
				<div class="app-main" style="padding-top:8px">
					<!-- BEGIN .main-heading -->
				
					<!-- END: .main-heading -->
                    <!-- BEGIN .main-content -->
                    {%block body %}
                    
                    {%endblock%}
					
			<!-- END: .main-footer -->
		</div>
		<!-- END: .app-wrap -->

		<!-- jQuery first, then Tether, then other JS. -->
		<script src="{{ url_for('static',filename='assets/admin/js/jquery.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/cssjs/tether.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/js/bootstrap.min.js')}}"> </script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/unifyMenu/unifyMenu.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/onoffcanvas/onoffcanvas.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/js/moment.js')}}"></script>

		<!-- Peity JS -->
		<script src="{{ url_for('static',filename='assets/admin/vendor/peity/peity.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/peity/custom-peity.js')}}"></script>

		<!-- Circliful js -->
		<script src="{{ url_for('static',filename='assets/admin/vendor/circliful/circliful.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/circliful/circliful.custom.js')}}"></script>

		<!-- Chartist JS -->
		<script src="{{ url_for('static',filename='assets/admin/vendor/chartist/js/chartist.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/chartist/js/chartist-tooltip.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/chartist/js/custom/custom-area-chart2.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/chartist/js/custom/custom-compare-line.js')}}"></script>

		<!-- Slimscroll JS -->
		<script src="{ url_for('static',filename='assets/admin/vendor/slimscroll/slimscroll.min.js')}}"></script>																																																			
		<script src="{ url_for('static',filename='assets/admin/vendor/slimscroll/custom-scrollbar.js')}}"></script>

		<!-- Common JS -->
		<script src="{{ url_for('static',filename='assets/admin/js/common.js')}}"></script>


	</body>

<!-- Mirrored from bootstrap.gallery/unify-admin/design-13/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 24 Jan 2019 06:04:06 GMT -->
</html>