modules/admin/routes.py
from flask import Flask, render_template, jsonify, request,redirect,url_for, request,json
from flask import session 
from flask import Blueprint
from modules.admin import Mails
from bson.json_util import dumps
import os
import datetime
from modules.database import collection
from modules.database import adminoperations as adminop
mod = Blueprint('admin',__name__,template_folder='templates')


@mod.route('/home')
def home():
    if  session['logged_in']== False:
        return redirect(url_for('visitor.index'))
    bully_data = adminop.getAllOffensivePosts()
    return render_template("bullydata.html",data=bully_data)

@mod.route('/sendmail/<title>/<body>/<receiver>')
def sendmail(title,body,receiver):
    return Mails.sendmail(title,body,receiver)

@mod.route('/getmail/<user>')
def getmail(user):
    return dumps(adminop.getMail(user))

@mod.route('/blockuser',methods=['POST'])
def blockuser():
    adminop.blockUser(request.json['uname'])
    return jsonify({"status":"success"})

@mod.route('/deletepost')
def deletepost(postid):
    adminop.delete_post(postid)
    
    return jsonify({"status":"success"})

@mod.route('/blockedusers')
def blockedusers():
    if session['logged_in'] == False:
        return redirect(url_for('visitor.index'))
    blocked_users = adminop.blocked_users()
    print(blocked_users)
    return render_template('blockedusers.html', blocked_users = blocked_users)

@mod.route('/unblock',methods=['POST'])
def unblock():
    adminop.unblock(request.json['uname'])
    return jsonify({"status":"success"})

@mod.route('/train')
def train():
    return render_template('train.html')

@mod.route('/admin_chatbot')
def admin_Chatbot():
    if  session['logged_in'] ==False :
        return redirect(url_for('visitor.index'))
    return render_template('admin_chatbot.html')

@mod.route('/update_chatbot/<content>')
def update_chatbot(content):
    filepath = os.getcwd()
    f = open(filepath+'/modules/chatbot/chatbot.txt',"a")
    f.write(content)
    f.close()
    datetimes=datetime.datetime.now().strftime("%I:%M%p on %B %d, %Y")
    collection.addnotification("all","contents of chatbot have been updated",datetimes)
    return jsonify({"status":"success"})
    

modules/admin/templates/admin_chatbot.html
<!DOCTYPE html>
<html>
{% extends "commonhtml.html" %}
<head>
  <title>Chat Bot</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css" />
  <link rel="stylesheet" href="{{ url_for('static',filename='assets/css/usercard.css')}}" />
  <script src="{{ url_for('static',filename='assets/js/sendmessageChatbot.js')}}"></script> 
  <script src="{{ url_for('static',filename='assets/js/jquery.min.js')}}"></script>
  <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous">     </script>
  <script src="{{ url_for('static',filename='assets/js/app-script.js')}}"></script>

 <script type="text/javascript">

 </script>

</head>

    {% block body %}
     

  

    <div class="row gutters" style="margin-bottom:16px;min-height:500px ;padding:0px;max-height:500px;margin-left: 8px;width:99%;overflow-y:scroll">
        
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6" >
            <div class="card" style="min-height:500px"> 
                <div class="card-header">Chat</div>
                <div class="customScroll">
                    <div class="card-body"style="margin-top:8px">
                        <ul class="chats" id="botchatslist">
                           
                           
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <div>
                <input type="text" id="botmsgtext" style="height:32px;border-color:green; ;width:250px;border-radius:8px;margin-left: 8px" placeholder="send a message"/>
                <input type="button" id="sendbotbtn"  class="btn btn-outline-success btn-rounded" width="100px" value="send message" onclick="talktobot()"/>
          </div>
       </div>
    

   {% endblock %}
  



    



  
  

  
      </html>

modules/admin/templates/blockedusers.html
{% extends "commonhtml.html"%}

{% block body %}



<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12" style="min-height:700px">
    <div class="card" style="width:800px">
        <div class="card-header">Blocked Users</div>
        <div class="card-body">
            <table class="table table-hover table-inverse m-0">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Unblock</th>
                    </tr>
                </thead>
                <tbody>
                    {% for b in blocked_users %}
                
                    <tr>
                        <th scope="row">{{loop.index}}</th>
                       
                        <td>{{b.fname}}</td>
                        <td>{{b.lname}}</td>
                        <td>{{b.uname}}</td>
                        <td>{{b.email}}</td>
                        <td> {{b.phone}}</td>
                        <td>  <button type="button" class="btn btn-outline-success btn-rounded" data-uname="{{b.uname}}" onclick="unblock_user(this)">Unblock</button>  </td>
                    </tr>
            {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
{% endblock %}

modules/admin/templates/bullydata.html
{% extends "commonhtml.html" %}

{% block body %}
<script src="{{ url_for('static',filename='assets/js/adminoperations.js')}}"></script>

<div class="row gutters" style="width:100%;align-content: center;background:#FFF">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <div class="card" style="width:1000px;align-content: center;min-height:700px">
            <div class="card-header">Cyber Offensive Contents Found</div>
            {% for d in data %}
            <div class="card-body" style="width:1000px">
                <div class="list-group" style="width:100%">
                  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                      <h5 id="postid">{{d.postid}}</h5>
                      <small id="post_time">on : {{d.time}}</small>
                    </div>
                    <p class="mb-1">post contents : <br> <br> <b>{{d.status}}</b> </p>
                    <small style="color:blue"> post owner : {{d.uname}}</small>
                  </a>
                
                </div>
                <br>
                <button type="button" class="btn btn-outline-success btn-rounded" id={{d.uname}} data-uname="{{d.uname}}" data-time="{{d.time}}" data-email="{{d.email}}" data-postid="{{d.postid}}" onclick="sendmail(this)">Send E-mail</button>
                <button type="button" class="btn btn-outline-success btn-rounded"onclick="deletepost(this)" data-postid="{{d.postid}}">Delete Post</button>
                <button type="button" data-uname="{{d.uname}}" class="btn btn-outline-success btn-rounded"onclick="block(this)">Block User</button>
            </div>
            {% endfor %}
        </div>
    </div>
   
       
        

{% endblock %}

modules/admin/templates/commonhtml.html
<!doctype html>
<html lang="en">
	
<!-- Mirrored from bootstrap.gallery/unify-admin/design-13/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 24 Jan 2019 06:02:52 GMT -->
<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="Unify Admin Panel" />
		<meta name="keywords" content="Analytics, CRM, Admin, Dashboard, Bootstrap4, Sass, CSS3, HTML5, Responsive Dashboard, Responsive Admin Template, Admin Template, Best Admin Template, Bootstrap Template, Themeforest" />
		<meta name="author" content="Bootstrap Gallery" />
		<link rel="shortcut icon" href="{{ url_for('static',filename='assets/admin/img/favicon.ico')}}"/>
		<title>Unify Admin Dashboard - Analytics</title>

		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
		
		<!-- Common CSS -->
		<!-- Common CSS -->
		<link rel="stylesheet" href="{{ url_for('static',filename='assets/admin/fonts/icomoon/icomoon.css')}}" />
		<link rel="stylesheet" href="{{ url_for('static',filename='assets/admin/css/bootstrap.min.css')}}" />
		<link rel="stylesheet" href="{{ url_for('static',filename='assets/admin/css/fonts/icomoon/icomoon.css')}}" />
		<link rel="stylesheet" href="{{ url_for('static',filename='assets/admin/css/main.css')}}" />

		<!-- Other CSS includes plugins - Cleanedup unnecessary CSS -->
		<!-- Chartist CSS -->
		<link href="{{ url_for('static',filename='assets/admin/vendor/chartist/css/chartist.min.css')}}" rel="stylesheet" />
		<link href="{{ url_for('static',filename='assets/admin/vendor/chartist/css/chartist-custom.css')}}" rel="stylesheet" />		

		<script src="{{ url_for('static',filename='assets/js/adminoperations.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/js/lobibox.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/js/sweetalert.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/js/notifications.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/js/sendmessageChatbot.js')}}"></script>
	</head>
	</head>
	<body>

		<!-- Loading starts -->
		
		<!-- Loading ends -->
		
		<!-- BEGIN .app-wrap -->
		<div class="app-wrap">
			<!-- BEGIN .app-heading -->
			<header class="app-header">
				<div class="container-fluid">
					<div class="row ">
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-8 col-8">
							<a href="index.html" class="logo">
								<img src="{{ url_for('static',filename='assets/admin/img/unify.png')}}"alt="Unify Admin Dashboard">
							</a><a class="mini-nav-btn" href="#" id="app-side-mini-toggler">
								<i class="icon-sort"></i>
							</a>
							<a href="#app-side" data-toggle="onoffcanvas" class="onoffcanvas-toggler" aria-expanded="true">
								<i class="icon-chevron-thin-left"></i>
							</a>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-4 col-4">
							<ul class="header-actions">
								<li class="dropdown">
									<a href="#" id="notifications" data-toggle="dropdown" aria-haspopup="true">
										<i class="icon-notifications_none" style="font-size:18px"></i>
										</span>
									</a>
									<div class="dropdown-menu dropdown-menu-right lg" aria-labelledby="notifications">
										<ul class="imp-notify">
											
												<div class="details">
													<p><span>Wilson</span> The best Dashboard design I have seen ever.</p>
												</div>
											</li>
											<li>
												<div class="icon">J</div>
												<div class="details">
													<p><span>John Smith</span> Jhonny sent you a message. Read now!</p>
												</div>
											</li>
											<li>
												<div class="icon secondary">R</div>
												<div class="details">
													<p><span>Justin Mezzell</span> Stella, Added you as a Friend. Accept it!</p>
												</div>
											</li>
										</ul>
									</div>
								</li>
								<li>
									<a href="{{url_for('admin.train')}}" id="todos" data-toggle="dropdown" aria-haspopup="true">
										<i class="icon-person_outline" style="font-size:18px"> Train ChatBot</i>
									</span>
									</a>
									<div class="dropdown-menu dropdown-menu-right lg" aria-labelledby="todos">
										<ul class="stats-widget">
				              <li>
				                <h4>$37895</h4>
				                <p>Revenue <span>+2%</span></p>
				                <div class="progress">
													<div class="progress-bar" role="progressbar" aria-valuenow="87" aria-valuemin="0" aria-valuemax="100" style="width: 87%">
														<span class="sr-only">87% Complete (success)</span>
													</div>
												</div>
				              </li>
				              <li>
				                <h4>4,897</h4>
				                <p>Downloads <span>+39%</span></p>
				                <div class="progress">
													<div class="progress-bar" role="progressbar" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100" style="width: 65%">
														<span class="sr-only">65% Complete (success)</span>
													</div>
												</div>
				              </li>
				              <li>
				                <h4>2,219</h4>
				                <p>Uploads <span class="text-secondary">-7%</span></p>
				                <div class="progress">
													<div class="progress-bar bg-danger" role="progressbar" aria-valuenow="42" aria-valuemin="0" aria-valuemax="100" style="width: 42%">
														<span class="sr-only">42% Complete (success)</span>
													</div>
												</div>
				              </li>
				            </ul>
				          </div>
								</li>
								<li class="dropdown">
									<a href="" id="userSettings" class="user-settings" data-toggle="dropdown" aria-haspopup="true">
									
										<i class="icon-chevron-small-down" style="font-size:18px"></i>
									</a>
									<div class="dropdown-menu lg dropdown-menu-right" aria-labelledby="userSettings">
										<ul class="user-settings-list">
											<li>
												<a href="profile.html">
													<div class="icon">
														<i class="icon-account_circle"></i>
													</div>
													<p>Profile</p>
												</a>
											</li>
											<li>
												<a href="profile.html">
													<div class="icon red">
														<i class="icon-cog3"></i>
													</div>
													<p>Settings</p>
												</a>
											</li>
											<li>
												<a href="filters.html">
													<div class="icon yellow">
														<i class="icon-schedule"></i>
													</div>
													<p>Activity</p>
												</a>
											</li>
										</ul>
										<div class="logout-btn">
											<a href="login.html" class="btn btn-primary">Logout</a>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</header>
			<!-- END: .app-heading -->
			<!-- BEGIN .app-container -->
			<div class="app-container">
				<!-- BEGIN .app-side -->
				<aside class="app-side" id="app-side">
					<!-- BEGIN .side-content -->
					<div class="side-content ">
						<!-- BEGIN .user-profile -->
						<div class="user-profile">
							<img src="{{ url_for('static',filename='assets/admin/img/user.png')}}" id="propic_master" class="profile-thumb" alt="User Thumb">
							<br>
							<br>
							<br>
							
							<h5 class="profile-name" id="username_master">ADMINISTRATOR</h5>
							
							<br>
							<br>
							<br>
							
							

							
							<ul class="profile-actions">
								<li>
									<a href="#">
										<i class="icon-social-skype"></i>
										<span class="count-label red"></span>
									</a>
								</li>
								<li>
									<a href="#">
										<i class="icon-social-twitter"></i>
									</a>
								</li>
								<li>
									<a href="login.html">
										<i class="icon-export"></i>
									</a>
								</li>
							</ul>
							<br>
							<br>
							<br>
							<br>
							<br>
						</div>
						<!-- END .user-profile -->
						<!-- BEGIN .side-nav -->
						<nav class="side-nav">
							<!-- BEGIN: side-nav-content -->
							<ul class="unifyMenu" id="unifyMenu">
								<li class="active selected">
									<a href="#" class="has-arrow" aria-expanded="false">
										<span class="has-icon">
											<i class="icon-laptop_windows"></i>
										</span>
										<span >Menu</span>
									</a>
									<ul aria-expanded="false" class="collapse in">
										
										<li>
											<a href="{{url_for('admin.home')}}"> <br>Review Posts<br>
												</a>
											
										</li>

										<li>
											<a href="{{url_for('admin.blockedusers')}}"> <br>Blocked Users<br>
												</a>
											
										</li>

										<li>
												<a href="{{url_for('admin.admin_Chatbot')}}"> <br>Chatbot<br>
													</a>
												
											</li>

										<li>
											<a href="{{url_for('visitor.logout')}}"> <br>Logout<br>
												</a>
											
										</li>
										
									  
									  
									</ul>
								</li>
							
									</ul>
								</li>
							</ul>
							<!-- END: side-nav-content -->
						</nav>
						<!-- END: .side-nav -->
					</div>
					<!-- END: .side-content -->
				</aside>
				<!-- END: .app-side -->

				<!-- BEGIN .app-main -->
				<div class="app-main" style="background:#FFF">
					<!-- BEGIN .main-heading -->
				
					<!-- END: .main-heading -->
                    <!-- BEGIN .main-content -->
                    {%block body %}
                    
                    {%endblock%}
					
			<!-- END: .main-footer -->
		</div>
		<!-- END: .app-wrap -->

		<!-- jQuery first, then Tether, then other JS. -->
		<script src="{{ url_for('static',filename='assets/admin/js/jquery.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/cssjs/tether.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/js/bootstrap.min.js')}}"> </script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/unifyMenu/unifyMenu.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/onoffcanvas/onoffcanvas.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/js/moment.js')}}"></script>

		<!-- Peity JS -->
		<script src="{{ url_for('static',filename='assets/admin/vendor/peity/peity.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/peity/custom-peity.js')}}"></script>

		<!-- Circliful js -->
		<script src="{{ url_for('static',filename='assets/admin/vendor/circliful/circliful.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/circliful/circliful.custom.js')}}"></script>

		<!-- Chartist JS -->
		<script src="{{ url_for('static',filename='assets/admin/vendor/chartist/js/chartist.min.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/chartist/js/chartist-tooltip.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/chartist/js/custom/custom-area-chart2.js')}}"></script>
		<script src="{{ url_for('static',filename='assets/admin/vendor/chartist/js/custom/custom-compare-line.js')}}"></script>

		<!-- Slimscroll JS -->
		<script src="{ url_for('static',filename='assets/admin/vendor/slimscroll/slimscroll.min.js')}}"></script>																																																			
		<script src="{ url_for('static',filename='assets/admin/vendor/slimscroll/custom-scrollbar.js')}}"></script>

		<!-- Common JS -->
		<script src="{{ url_for('static',filename='assets/admin/js/common.js')}}"></script>


	</body>

<!-- Mirrored from bootstrap.gallery/unify-admin/design-13/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 24 Jan 2019 06:04:06 GMT -->
</html>

modules/admin/templates/train.html
{% extends "commonhtml.html"%}

{% block body %}


<div class="form-group m-0" style="padding:32px ; min-height:800px" >
        <label for="exampleFormControlTextarea1">Update the chatbot knowledge</label>
        <textarea class="form-control" id="chatbotdatatext" rows="15"></textarea> <br>
        <button type="button" class="btn btn-outline-success btn-rounded" onclick="updateChatbot()">Upload Data</button>
    </div>

{% endblock %}